export const FETCH_CURRENCY_LIST = 'FETCH_CURRENCY_LIST';
export const FETCH_CURRENCY_LIST_SUCCESS = 'FETCH_CURRENCY_LIST_SUCCESS';
export const FETCH_CURRENCY_LIST_ERROR = 'FETCH_CURRENCY_LIST_ERROR';
export const RESET_INITIAL_STATE = 'RESET_INITIAL_STATE';
